# Site settings
title: WOWHHH
subtitle: [Patient & Keep Learning]
# keywords: emm
# description: 
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.oukohou.wang/" # 你的域名
page_no_title: "wow's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: wowhhh
email: yibowangcz@qq.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: Home
    directory: .
    icon: icon-home
  - page: Archive
    directory: archives/
    icon: icon-archive
  - page: Tag
    directory: tags/
    icon: icon-tags
  # - page: 留言
  #   directory: guestbook/
  #   icon: icon-guestbook
  - page: About
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # Links

  - title: wowhhh's github
    url: https://github.com/wowhhh
  - title: Tomcat Source Code Learning
    url: https://www.iteye.com/category/53603
#  - title:
#    url: http://jekyllcn.com/


# Google Analytics
ga_track_id: 'UA-176924326-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Code hub settings
codehub: # Code Hub
  - title: Github
    url: https://github.com/wowhhh


valine:
  enable: true
  app_id:  lOwrLdTKmNSdec8j7McNzeY5-gzGzoHsz
  app_key: SMPeHLC4dqVWziE3KakiDWVt
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: - 昵称 评论可显示此ID；\n - 邮箱 仅后台可见，用于后续交流;\n - 网址 可以是您的主页。\n上述内容皆为空，评论仍会显示……
  guest_info: nick,mail,link
  pageSize: 10
